---
deployment:
  tasks:
    # !!Careful what you deploy!!
    # (don't use wildcard, can't deploy /.git/)
    - export DEPLOYPATH=/home/excelsio1/public_html/
    # Add files in master to deployment
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp index.css $DEPLOYPATH
    # Add whole folders to deployment
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R logos $DEPLOYPATH
    - /bin/cp -R pictures $DEPLOYPATH