---
deployment:
  tasks:
    ### ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ### !! CAUTION: DEPLOYMENT TO INTERNET !!
    ### ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ## ! Don't use wildcard char
    ##   Can't deploy folders like "/.git/"

    # Specify DEPLOYPATH
    - export DEPLOYPATH=/home/excelsio1/public_html/

    # Deploy page html, css
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp index.css $DEPLOYPATH
    # Deploy asset folders
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R logos $DEPLOYPATH
    - /bin/cp -R pictures $DEPLOYPATH